"""
End-to-end regression for mass-aware optimization through
ThermalOptimizer.
 
The regression verifies that:
 
- ThermalOptimizer generates physically complete candidates.
- Every candidate has positive finite volume and mass.
- A mass-weighted optimizer run uses the real candidate mass.
- A mass-aware Pareto run returns only non-dominated
  optimizer-generated candidates.
- Legacy minimum-thermal-resistance behavior remains
  available and unchanged.
"""
 
import math
 
from core.objective_registry import (
    MASS_OBJECTIVE,
    THERMAL_RESISTANCE_OBJECTIVE,
)
from core.thermal_optimizer import ThermalOptimizer
from models.optimization_selection import (
    OptimizationSelectionConfiguration,
    OptimizationSelectionMode,
)
from models.requirements import (
    Constraints,
    EngineeringRequirements,
    Requirements,
)
from models.scoring_configuration import (
    ObjectiveWeight,
    ScoringConfiguration,
)
 
 
def create_requirements(
) -> EngineeringRequirements:
    """
    Create a compact but non-trivial design envelope.
 
    The envelope must contain candidates with different
    material masses and thermal resistances.
    """
 
    return EngineeringRequirements(
        component_type="heat_sink",
        convection_mode="forced",
        requirements=Requirements(
            heat_load=165.0,
            ambient_temperature=30.0,
            air_velocity=5.0,
        ),
        constraints=Constraints(
            base_length=50.0,
            base_width=50.0,
            max_height=12.0,
        ),
    )
 
 
def create_mass_weighted_configuration(
) -> OptimizationSelectionConfiguration:
    """
    Prefer low mass while retaining a thermal-performance
    contribution.
    """
 
    return OptimizationSelectionConfiguration(
        mode=(
            OptimizationSelectionMode
            .WEIGHTED_SCORE
        ),
        objectives=(
            THERMAL_RESISTANCE_OBJECTIVE,
            MASS_OBJECTIVE,
        ),
        scoring_configuration=(
            ScoringConfiguration(
                objective_weights=(
                    ObjectiveWeight(
                        objective_key=(
                            "thermal_resistance"
                        ),
                        weight=0.25,
                    ),
                    ObjectiveWeight(
                        objective_key="mass",
                        weight=0.75,
                    ),
                )
            )
        ),
    )
 
 
def create_mass_pareto_configuration(
) -> OptimizationSelectionConfiguration:
    """
    Create a thermal-resistance versus mass Pareto
    configuration.
    """
 
    return OptimizationSelectionConfiguration(
        mode=(
            OptimizationSelectionMode
            .PARETO_FRONT
        ),
        objectives=(
            THERMAL_RESISTANCE_OBJECTIVE,
            MASS_OBJECTIVE,
        ),
    )
 
 
def assert_candidate_physical_state(
    candidate,
    candidate_label: str,
) -> None:
    """
    Verify the physical state generated by ThermalOptimizer.
    """
 
    assert math.isfinite(
        candidate.solid_volume
    ), (
        f"{candidate_label}: solid volume must be finite."
    )
 
    assert candidate.solid_volume > 0.0, (
        f"{candidate_label}: solid volume must be positive."
    )
 
    assert math.isfinite(
        candidate.mass
    ), (
        f"{candidate_label}: mass must be finite."
    )
 
    assert candidate.mass > 0.0, (
        f"{candidate_label}: mass must be positive."
    )
 
 
def dominates(
    first_candidate,
    second_candidate,
) -> bool:
    """
    Return True when the first candidate dominates the
    second for the two minimization objectives used here.
    """
 
    no_worse = (
        first_candidate.thermal_resistance
        <= second_candidate.thermal_resistance
        and first_candidate.mass
        <= second_candidate.mass
    )
 
    strictly_better = (
        first_candidate.thermal_resistance
        < second_candidate.thermal_resistance
        or first_candidate.mass
        < second_candidate.mass
    )
 
    return no_worse and strictly_better
 
 
def main() -> None:
    requirements = create_requirements()
 
    optimizer = ThermalOptimizer()
 
    # --------------------------------------------------
    # Legacy/default optimizer run
    # --------------------------------------------------
 
    legacy_result = optimizer.optimize_with_details(
        requirements
    )
 
    assert legacy_result.has_feasible_design
 
    assert legacy_result.candidates
 
    assert (
        legacy_result.feasible_candidate_count
        == len(legacy_result.candidates)
    )
 
    for index, candidate in enumerate(
        legacy_result.candidates,
        start=1,
    ):
        assert_candidate_physical_state(
            candidate,
            f"Legacy candidate {index}",
        )
 
    legacy_selected_candidate = (
        legacy_result.selected_candidate
    )
 
    assert legacy_selected_candidate is not None
 
    lowest_resistance_candidate = min(
        legacy_result.candidates,
        key=lambda candidate: (
            candidate.thermal_resistance
        ),
    )
 
    assert (
        legacy_selected_candidate
        == lowest_resistance_candidate
    )
 
    # --------------------------------------------------
    # Mass-weighted end-to-end optimizer run
    # --------------------------------------------------
 
    weighted_result = optimizer.optimize_with_details(
        requirements,
        selection_configuration=(
            create_mass_weighted_configuration()
        ),
    )
 
    assert weighted_result.has_feasible_design
 
    assert weighted_result.candidates
 
    assert weighted_result.selection_result is not None
 
    assert (
        weighted_result
        .selection_result
        .uses_weighted_selection
    )
 
    weighted_candidate = (
        weighted_result.selected_candidate
    )
 
    assert weighted_candidate is not None
 
    assert_candidate_physical_state(
        weighted_candidate,
        "Mass-weighted selected candidate",
    )
 
    assert (
        weighted_candidate
        in weighted_result.candidates
    )
 
    weighted_analysis = (
        weighted_result
        .selection_result
        .weighted_result
        .best_candidate
    )
 
    weighted_mass_value = (
        weighted_analysis
        .scored_candidate
        .analysis
        .raw_report
        .get_value("mass")
    )
 
    assert math.isclose(
        weighted_mass_value,
        weighted_candidate.mass,
        rel_tol=0.0,
        abs_tol=1e-12,
    )
 
    mass_contribution = (
        weighted_analysis
        .scored_candidate
        .get_contribution("mass")
    )
 
    assert (
        mass_contribution.objective
        is MASS_OBJECTIVE
    )
 
    assert math.isfinite(
        mass_contribution.weighted_value
    )
 
    # The strongly mass-weighted run should not choose a
    # candidate heavier than the pure thermal optimum.
    assert (
        weighted_candidate.mass
        <= legacy_selected_candidate.mass
    )
 
    # --------------------------------------------------
    # Mass-aware Pareto end-to-end optimizer run
    # --------------------------------------------------
 
    pareto_result = optimizer.optimize_with_details(
        requirements,
        selection_configuration=(
            create_mass_pareto_configuration()
        ),
    )
 
    assert pareto_result.has_feasible_design
 
    assert pareto_result.selection_result is not None
 
    assert (
        pareto_result
        .selection_result
        .uses_pareto_selection
    )
 
    pareto_candidates = (
        pareto_result.selected_candidates
    )
 
    assert pareto_candidates
 
    for index, candidate in enumerate(
        pareto_candidates,
        start=1,
    ):
        assert_candidate_physical_state(
            candidate,
            f"Pareto candidate {index}",
        )
 
        assert candidate in pareto_result.candidates
 
    # --------------------------------------------------
    # Every returned Pareto candidate must be
    # non-dominated by every feasible optimizer candidate.
    # --------------------------------------------------
 
    for pareto_candidate in pareto_candidates:
 
        for feasible_candidate in (
            pareto_result.candidates
        ):
            assert not dominates(
                feasible_candidate,
                pareto_candidate,
            ), (
                "Pareto selection returned a candidate "
                "dominated in thermal resistance and mass."
            )
 
    # --------------------------------------------------
    # Every excluded candidate must be dominated by at
    # least one returned Pareto candidate.
    # --------------------------------------------------
 
    excluded_candidates = [
        candidate
        for candidate in pareto_result.candidates
        if candidate not in pareto_candidates
    ]
 
    assert excluded_candidates
 
    for excluded_candidate in excluded_candidates:
 
        assert any(
            dominates(
                pareto_candidate,
                excluded_candidate,
            )
            for pareto_candidate in pareto_candidates
        ), (
            "A non-selected optimizer candidate was not "
            "dominated by the returned Pareto front."
        )
 
    # --------------------------------------------------
    # The thermal and minimum-mass extremes must appear
    # on the thermal-resistance/mass Pareto front.
    # --------------------------------------------------
 
    pareto_minimum_thermal_candidate = min(
        pareto_result.candidates,
        key=lambda candidate: (
            candidate.thermal_resistance
        ),
    )
 
    pareto_minimum_mass_candidate = min(
        pareto_result.candidates,
        key=lambda candidate: (
            candidate.mass
        ),
    )
 
    assert (
        pareto_minimum_thermal_candidate
        in pareto_candidates
    )
 
    assert (
        pareto_minimum_mass_candidate
        in pareto_candidates
    )
 
    assert (
        pareto_minimum_mass_candidate.mass
        <= pareto_minimum_thermal_candidate.mass
    )
 
    print(
        "ALL END-TO-END OPTIMIZER MASS "
        "OBJECTIVE CHECKS PASSED"
    )
 
 
if __name__ == "__main__":
    main()