"""
engineering_assessment.py
 
Structured deterministic engineering judgment produced
by a rule-based evaluator.
 
An EngineeringAssessment is different from an
EngineeringInsight:
 
- EngineeringInsight reports deterministic facts.
- EngineeringAssessment interprets those facts using an
  explicit engineering rule.
 
Assessments must remain deterministic, traceable, and
independent of any LLM.
"""
 
from dataclasses import dataclass
 
from models.engineering_category import (
    EngineeringCategory,
)
from models.engineering_evidence import (
    EngineeringEvidence,
)
from models.engineering_severity import (
    EngineeringSeverity,
)
 
 
@dataclass(frozen=True)
class EngineeringAssessment:
    """
    One traceable engineering judgment generated by an
    explicit deterministic rule.
 
    Parameters
    ----------
    assessment_id:
        Stable unique identifier for the assessment.
 
    rule_id:
        Stable identifier of the rule that produced the
        assessment.
 
    severity:
        Importance and urgency of the assessment.
 
    category:
        Engineering discipline associated with the rule.
 
    title:
        Short user-facing assessment title.
 
    summary:
        Deterministic explanation of the rule outcome.
 
    evidence:
        Structured facts supporting the assessment.
 
    source_insight_ids:
        IDs of the EngineeringInsight objects interpreted
        by the evaluator.
 
    recommendation:
        Optional deterministic corrective or follow-up
        action.
 
    passed:
        True when the evaluated rule is satisfied, False
        when the rule identifies a concern.
    """
 
    assessment_id: str
 
    rule_id: str
 
    severity: EngineeringSeverity
 
    category: EngineeringCategory
 
    title: str
 
    summary: str
 
    evidence: tuple[
        EngineeringEvidence,
        ...,
    ] = ()
 
    source_insight_ids: tuple[
        str,
        ...,
    ] = ()
 
    recommendation: str = ""
 
    passed: bool = False
 
    def __post_init__(
        self,
    ) -> None:
        """
        Validate the structured assessment definition.
        """
 
        if not isinstance(
            self.assessment_id,
            str,
        ):
            raise ValueError(
                "'assessment_id' must be a string."
            )
 
        normalized_assessment_id = (
            self.assessment_id.strip()
        )
 
        if not normalized_assessment_id:
            raise ValueError(
                "Engineering assessment ID cannot be "
                "empty."
            )
 
        object.__setattr__(
            self,
            "assessment_id",
            normalized_assessment_id,
        )
 
        if not isinstance(
            self.rule_id,
            str,
        ):
            raise ValueError(
                "'rule_id' must be a string."
            )
 
        normalized_rule_id = (
            self.rule_id.strip()
        )
 
        if not normalized_rule_id:
            raise ValueError(
                "Engineering rule ID cannot be empty."
            )
 
        object.__setattr__(
            self,
            "rule_id",
            normalized_rule_id,
        )
 
        if not isinstance(
            self.severity,
            EngineeringSeverity,
        ):
            raise ValueError(
                "'severity' must be an "
                "EngineeringSeverity value."
            )
 
        if not isinstance(
            self.category,
            EngineeringCategory,
        ):
            raise ValueError(
                "'category' must be an "
                "EngineeringCategory value."
            )
 
        if not isinstance(
            self.title,
            str,
        ):
            raise ValueError(
                "'title' must be a string."
            )
 
        normalized_title = self.title.strip()
 
        if not normalized_title:
            raise ValueError(
                "Engineering assessment title cannot "
                "be empty."
            )
 
        object.__setattr__(
            self,
            "title",
            normalized_title,
        )
 
        if not isinstance(
            self.summary,
            str,
        ):
            raise ValueError(
                "'summary' must be a string."
            )
 
        normalized_summary = self.summary.strip()
 
        if not normalized_summary:
            raise ValueError(
                "Engineering assessment summary cannot "
                "be empty."
            )
 
        object.__setattr__(
            self,
            "summary",
            normalized_summary,
        )
 
        if not isinstance(
            self.evidence,
            tuple,
        ):
            raise ValueError(
                "'evidence' must be a tuple."
            )
 
        for evidence_item in self.evidence:
            if not isinstance(
                evidence_item,
                EngineeringEvidence,
            ):
                raise ValueError(
                    "Every assessment evidence item must "
                    "be an EngineeringEvidence object."
                )
 
        if not isinstance(
            self.source_insight_ids,
            tuple,
        ):
            raise ValueError(
                "'source_insight_ids' must be a tuple."
            )
 
        normalized_source_ids: list[str] = []
 
        for source_insight_id in (
            self.source_insight_ids
        ):
            if not isinstance(
                source_insight_id,
                str,
            ):
                raise ValueError(
                    "Every source insight ID must be a "
                    "string."
                )
 
            normalized_source_id = (
                source_insight_id.strip()
            )
 
            if not normalized_source_id:
                raise ValueError(
                    "Source insight IDs cannot be empty."
                )
 
            normalized_source_ids.append(
                normalized_source_id
            )
 
        if (
            len(set(normalized_source_ids))
            != len(normalized_source_ids)
        ):
            raise ValueError(
                "Source insight IDs must be unique within "
                "one engineering assessment."
            )
 
        object.__setattr__(
            self,
            "source_insight_ids",
            tuple(normalized_source_ids),
        )
 
        if not isinstance(
            self.recommendation,
            str,
        ):
            raise ValueError(
                "'recommendation' must be a string."
            )
 
        object.__setattr__(
            self,
            "recommendation",
            self.recommendation.strip(),
        )
 
        if not isinstance(
            self.passed,
            bool,
        ):
            raise ValueError(
                "'passed' must be a bool."
            )
 
    @property
    def has_evidence(
        self,
    ) -> bool:
        """
        Return True when structured supporting evidence
        is attached.
        """
 
        return bool(self.evidence)
 
    @property
    def has_source_insights(
        self,
    ) -> bool:
        """
        Return True when the assessment traces back to one
        or more deterministic insights.
        """
 
        return bool(
            self.source_insight_ids
        )
 
    @property
    def has_recommendation(
        self,
    ) -> bool:
        """
        Return True when the rule provides a deterministic
        follow-up action.
        """
 
        return bool(self.recommendation)